### ISSUE TITLE
Albino Elf Swordsman redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#115]
Albino Elf Swordsman redone using Fighter-M-01 light.png and Townfolk-Adult-M-004 light.png from 24x32 characters pack extended by diamonddmgirl and 32x32.png from 'SHROOMBLADE 2 SIZES ( https://opengameart.org/content/shroomblade-2-sizes )(Justis)(CC0) colorized with porcini's probably main color instead of original.
![raelfsm](https://user-images.githubusercontent.com/37004874/38171746-b5834874-356d-11e8-9a35-4c501ff692a0.png)
Some work
![shroomswordwork](https://user-images.githubusercontent.com/37004874/38171747-c3759d10-356d-11e8-9a5b-7d6543906299.png)
![raelfsminm](https://user-images.githubusercontent.com/37004874/38171749-c7326a28-356d-11e8-9e59-a884061a9309.png)
![smallarmwork](https://user-images.githubusercontent.com/37004874/38171750-c912fdd0-356d-11e8-8d17-2cd137341907.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: e50b0a7

I remember diamonddmgirl exposing an error in some of Cabbit's sprites. In the north-facing frames, the legs & arms are reversed. E.g., instead of *left leg forward* + *left arm backward*, it's *left leg forward* + *left arm forward*. This sprite appears to contain that error. It's not a problem & doesn't need fixed. If we want it fixed, it can be done later.

For future reference, you may want to check Cabbit's/diamonddmgirl's sprites against my Cabbit bases edits:
1. https://github.com/AntumDeluge/cabbit-bases-collection/tree/master/art/sprite/parts/body/unisex-AA1
2. https://github.com/AntumDeluge/cabbit-bases-collection/tree/master/art/sprite/base/human/unisex-AA1

In my latest Git version, the body type *unisex-AA1* is the same as Cabbit's originals, but are all formatted as *left leg forward* + *left arm backward*. My [Cabbit Collection](https://github.com/AntumDeluge/cabbit-collection/tree/master/art/sprite) sprites have not all been fixed yet.

**Comment by AntumDeluge** [comment]
With Cabbit's bases & sprites, I've tried to follow the format of placing *left leg forward* + *left arm backward* as the first frame for each row.
