### ISSUE TITLE
Balancing of RATK

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#212]
RATK is a new stat that is used for range combat. This stat needs to be balanced for new players, average players, and old players (>= level 50).

Normal ATK is only increased when you are hit by an enemy, this makes camping low level creates a bit harder.

It may or may not be a good idea to derive the initial value from another stat such as ATK or probably better level as level is harder to camp for than ATK.

There is a maximum value for the training facility, which needs to be determined on solid grounds.

**Comment by nhnb** [comment]
I am considering to revert the RATK changes next week, unless there is a significant progress towards balancing or it is hidden behind a switch. We cannot delay the next release indefinitely and I am in no position to deal with these issues on my own.

**Comment by nhnb** [comment]
I managed to do the complete revert in one single commit. So it should be easy to re-add it after balancing.

**Comment by AntumDeluge** [comment]
I will re-open this issue if I start to work on the RATK stat again, which for sure won't be until after 1.32 release.

**Comment by AntumDeluge** [comment]
I have re-implemented the RATK stat: 580bd9c1e42cf896899f5e232ad50dfb5baf61a7

Since players are at much less risk of being hit by an enemy, this stat would be much more difficult to train were players only to receive XP after being hit. So, in the case of range attacks, players receive XP for each successful hit & none if the hit misses or is blocked.

As for setting the stat for current players, perhaps it would be good to initialize it using their curring ATK level, something like `ATK_XP / 2`.

The archery range has also been re-implemented:
- new implementation of FlyOverArea (cd62483fbf3805b1d7b06df6e65a8e7e7b180816 & 07497aea69f7aa2170e73ce62b770a45a4f921c0)
- re-implement archery range (33cf0ed3d6ad73ab146e21910ae66129a78b7d3b)

Currently, players can use the archery range until their RATK level is at 80. They can train for 15 minutes at a time for the price of 10,000 money & must wait 6 hours before entering the range again. These options can be changed if we decide on better level limit, train time limit, or price.

**Comment by AntumDeluge** [comment]
RATK disabled for 1.34 release.
