### ISSUE TITLE
turn Keyring from 2x4 into 3x3 slot allowance (both in GUI and internal)  

### ISSUE THREAD

**Issue by nylon0700** [arianne/stendhal#264]
## 💡 Describe your idea
Make Keyring  container take up less vertical space in character/player panel

## 🔬 Motivation
Keyring  container is 2x4 in player/character panel
Keyring container should take less vertical space in player/character panel
 
A clear description of the background or motivation for the feature request. What problem is solved?
Less vertical space wasted,
1x4 empty space on character/player interface is wasted

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
I recommend using the dimensions of the 3x3 layout with an unusable slot/area at the end so it is still 8 slots.

Mockup: 
![keyring_layout_mockup](https://user-images.githubusercontent.com/3631473/70387049-34fafd00-1955-11ea-89a2-3e8868f7f63a.png)

This might take some modifying of client slot windows.

**Comment by nhnb** [comment]
I have the feeling, that we are trying to fix a workaround instead of the original problem.

The keyring was designed as 4x2 intentionally to make it look very different from the bag.

 I got the impression that the motivation to change that format is based on the desire to have more screenspace for the scroll wallet. But a reduction of the keyring from 4 to 3 rows, does not really help here, at least on my screen.

Perhaps we should consider making opening and closing more prominent? I assume items in the keyring are not accessed regularly. The scroll wallet could also be a popup. But I am not sure if the extra click is an issue, when a player tries to do a quick escape from a deadly situation

**Comment by AntumDeluge** [comment]
It's not too important to me either way. And ya, keyring items are probably not used frequently. The only situation that I can think of where quick access to the keyring would be desired would be what you described above with scrolls, if a player wants to use their wedding ring to escape a dangerous situation.

**Comment by nylon0700** [comment]
keyring:
 Layout 4x2 (2x4) wastes vertical space when kept open...
 What rings can be stored in keyring?

portfolio (scroll wallet):
 can hold emergency ´get out of here´ when kept open

keyring and portfolio could coexist fine
making them popups instead of fixed panels? mmm... like 10years ago?
