### ISSUE TITLE
Have NPC indicated in minimap/zone

### ISSUE THREAD

**Issue by nylon0700** [arianne/stendhal#272]
## 💡 Describe your idea
Have NPC indicated in minimap (zone) with a colored + mark
Players are indicated with a + (white) mark on minimap (zone)
NPC could be indicated with a + (different color) mark  on minimap (zone)

## 🔬 Motivation
Make NPC a Point of Interest on minimap (zone)

**Comment by cosminhume** [comment]
Sometimes I wish too I could see NPCs on the minimap. :grin:
At the same time, I think having them hidden might be on purpose, to make the game a bit more interesting. It's a pleasant surprise to encounter one when exploring new territory.
At least, if this would be implemented there would have to be an exception for [Amber](https://stendhalgame.org/npc/Amber.html) ([Jef](https://stendhalgame.org/npc/Jef.html)'s mother), because the quest is exactly to find her.

**Comment by nylon0700** [comment]
> Sometimes I wish too I could see NPCs on the minimap. grin
> At the same time, I think having them hidden might be on purpose, to make the game a bit more interesting. It's a pleasant surprise to encounter one when exploring new territory.
> At least, if this would be implemented there would have to be an exception for [Amber](https://stendhalgame.org/npc/Amber.html) ([Jef](https://stendhalgame.org/npc/Jef.html)'s mother), because [the quest](https://stendhalgame.org/quest/find_jefs_mother.html) is exactly to find her.

Possibly the other teleporting NPCs too, like the flower seller Rose and Mizuno.

**Comment by AntumDeluge** [comment]
Just a note: The web client currently displays the location of NPCs on the minimap. Not sure if this will persist in future versions.

I think displaying NPCs in minimap is fine, as long as in the circumstances mentioned above, they are hidden.

**Comment by AntumDeluge** [comment]
NPCs now support a "hidden" attribute which is used for website to supress showing location. But it could also be used for determining if an NPC is visible on minimap.

**Comment by AntumDeluge** [comment]
Closing in favor of #686
