### ISSUE TITLE
Someone is Trolling Ados Market

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#309]
There is a [large troll](https://github.com/arianne/stendhal/blob/82ee04cd7857c752983d5999c55abe6904426382/data/sprites/npc/adosmarketgrocerysellernpc.png) roaming around Ados's market area, scaring away potential customers.

![stendhal-2020 01 06-17 41 38](https://user-images.githubusercontent.com/3631473/71861668-f7040c80-30ab-11ea-92cc-3b2c274b7720.png)

**Comment by nylon0700** [comment]
Description: You see Ambrogita, a busy market place seller

Questions:
#1) Since when NPCs are a threat to players?
#2) What makes Ambrogita a troll, being trolling or a scary presence in Ados market?
#2b) What action(s) does Ambrogita do to scare potential customers of Ados market?
#3) Does Ambrogita have something to sell by her stand in Ados market?

Ambrogita might not look as Barbie and might look a bit scaring at first sight...
Definitely not trolling.
