### ISSUE TITLE
Server hangs on shutdown in development environment

### ISSUE THREAD

**Issue by ghost** [arianne/stendhal#358]
## 🐞 Describe the bug

In my development environment, initialized years ago, I couldn't stop the server anymore.

## 🔥 How to reproduce

1. In Eclipse, start `StendhalServer`
2. In Eclipse, start the Java client (`Starter`)
3. Connect with the development client to the development server, play around
4. Stop the client by closing the game window
5. Click `Terminate` (🟥) in the Eclipse Console corresponding to the server

Expected: the server shuts down
Actual:

- Eclipse complains about not being able to terminate the process
- the Java process with the server continues to run and doesn't respond to `SIGTERM`

Unfortunately, after some changes in the environment I am **no longer able to reproduce** the issue.
What I did:

- sent `SIGQUIT` (`kill -3`) to the hanging process
- saw [the thread dump](https://github.com/arianne/stendhal/files/4397436/kill-3.log) in the server's console
- heard the CPU fan running for about a minute
- saw [an `OutOfMemoryError`](https://github.com/arianne/stendhal/files/4397437/oom.log) in the server console
- ran `jstack` on the hanging process
- saw the [new thread dump](https://github.com/arianne/stendhal/files/4397438/jstack.log)
- sent `SIGKILL` (`kill -KILL`) to the hanging process
- based on the thread dumps, suspected there was something wrong with the H2 database
- renamed the database file (`h2db.h2.db`) to something else (to have a backup) and deleted the lock file (`h2db.lock.db`)
- started the server again, with a fresh database
- could no longer reproduce
- reverted to the initial database file
- could not reproduce with that either

## 🌍  Environment

Java client (probably not relevant)

Ubuntu 19.10

```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

```
Eclipse IDE for Java Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211
OS: Linux, v.5.3.0-42-generic, x86_64 / gtk 3.24.12, WebKit 2.26.4
Java version: 1.8.0_242
```

## 🛠️ Suggested fixes

Ideas on how to fix the problem: analyze the thread dumps.

## 🔭 Additional information

- the output of `kill -3`: [kill-3.log](https://github.com/arianne/stendhal/files/4397436/kill-3.log)
- the `OutOfMemoryError` after `kill -3`: [oom.log](https://github.com/arianne/stendhal/files/4397437/oom.log)
- the output of `jstack`: [jstack.log](https://github.com/arianne/stendhal/files/4397438/jstack.log)

**Comment by nhnb** [comment]
Let's see:

- Thread `Thread-3` tried to initiate a shutdown because `MarauroaUncaughtExceptionHandler` detected that this thread was killed by an uncaught exception. `Thread-3`, however, hangs because another therad has already initiated the shutdown sequence. To be precise `Thread 3` hangs on `0x00000000f837d620` which is owned by thread `SIGTERM handler`

- Thread `SIGTERM handler` has initiated the shutdown. It is currently executing shutdown hooks and waiting for a thread based on the class `marauroa.server.marauroad$2` to complete. This is `Thread-3`.

All the other threads are irrelevant:

- Threads `marauroad`, `DelayedEventHandlerThread`, `GameServerManager` and  `DBCommandQueue` are all waiting in a loop that will end as soon as a `finished` flag is set.

- Threads `DestroyJavaVM`, `VM Thread`, `GC task thread#*` and `VM Periodic Task Thread`  are java threads that will not prevent shutdown

- Threads `Attach Listener`, `H2 Log Writer H2DB`, `H2 File Lock Watchdog`, `Abandoned connection cleanup thread`, `Service Thread`, `C2 CompilerThread*`, `Signal Dispatcher`, `Finalizer` amd `Reference Handler` are daemon threads. The daemon flag means that such a thread will not prevent shutdown.

To summarize: 

`SIGTERM handler` started the shutdown sequence and is hold a lock on the shutdown. It is currently waiting for `Thread-3` to execute shutdown hooks. `Thread-3` ran into an unexpected and uncaught exception. Therefore it started the shutdown sequence on its own.  But since the shutdown sequence is already in progress, it cannot obtain the lock. Both threads are waiting on each other and will never complete.

The unexpected and uncaught exception is the OutOfMemoryError you posted. It did occur in `Thread-3`. It is an "error", so it will not be caught by standard exception handlers. At the time of the OOMError, it was making a copy of a zone storage in order to write it to the database. Due to the asynchronous natures of memory allocation, the real issue might be elsewhere. But if you put a lot of stuff into zone-storage, this is a likely cause.

A simple solution is to increase the maximum heap size for the java process. It is currently set to `-Xmx128m`.

**Comment by cosminhume** [comment]
Thanks for the detailed analysis!
From my point of view, this issue can be considered closed.
